<script setup lang="ts">
import { ref, onMounted } from "vue";
import { useI18n } from "vue-i18n";
import { useTheme, useDisplay } from "vuetify";
import { storeToRefs } from "pinia";
import {
  addRomCheat,
  updateRomCheat,
  deleteRomCheat,
  uploadCheatFile,
  getCheatFiles,
  deleteCheatFile,
  getCheatCodes,
} from "@/services/api/cheat";
import romApi from "@/services/api/rom";
import storeAuth from "@/stores/auth";
import type { DetailedRom } from "@/stores/roms";
import type { CheatFile } from "@/services/api/cheat";

interface ExtendedCheatFile extends CheatFile {
  size: number;
  updated_at: string;
  path: string;
}

interface ExtendedDetailedRom extends DetailedRom {
  cheats?: any[];
  cheat_files?: CheatFile[];
}

const props = defineProps<{ rom: ExtendedDetailedRom }>();
const { t } = useI18n();
const theme = useTheme();
const auth = storeAuth();
const newCheatFile = ref<File | null>(null);
const { scopes } = storeToRefs(auth);
const activeTab = ref("cheatcodes");
const { mdAndDown } = useDisplay();

const cheats = ref(
  (props.rom.cheats ?? []).map((cheat) => ({
    ...cheat,
    isEditing: false,
    editName: cheat.name,
    editCode: cheat.code,
    editDescription: cheat.description,
  })),
);

const newCheat = ref({
  name: "",
  code: "",
  description: "",
  type: "raw", // Default type
});

// Fetch cheats from the backend
async function refreshCheats() {
  try {
    const response = await getCheatCodes(props.rom.id.toString());
    if (response && Array.isArray(response)) {
      cheats.value = response.map((cheat) => ({
        ...cheat,
        isEditing: false,
        editName: cheat.name,
        editCode: cheat.code,
        editDescription: cheat.description,
        type: cheat.type || "raw", // Ensure type is preserved and has a default
        formattedType: formatCheatType(cheat.type || "raw"), // Add formatted type for display
      }));
    }
  } catch (error) {
    console.error("Failed to fetch cheats:", error);
  }
}

// Load cheats when component is mounted
onMounted(() => {
  refreshCheats();
  refreshCheatFiles();
});

async function addCheat() {
  if (!newCheat.value.name || !newCheat.value.code) return;

  try {
    console.log("Adding cheat:", newCheat.value);
    const result = await addRomCheat(props.rom.id.toString(), {
      id: "", // Will be generated by the server
      name: newCheat.value.name,
      code: newCheat.value.code,
      description: newCheat.value.description,
      type: newCheat.value.type,
      romId: props.rom.id.toString(),
    });

    console.log("Add cheat result:", result);
    if (result?.id) {
      await refreshCheats(); // Refresh cheats after adding
      newCheat.value = { name: "", code: "", description: "", type: "raw" }; // Reset to default values
    } else {
      console.error("Failed to add cheat code: No ID returned from server");
      alert(t("cheat.addFailed"));
    }
  } catch (error: any) {
    console.error("Failed to add cheat code:", error);
    alert(t("cheat.addFailed") + ": " + (error.message || "Unknown error"));
  }
}

function toggleEdit(cheat: any) {
  cheat.isEditing = !cheat.isEditing;
}

async function saveEdit(cheat: any) {
  const result = await updateRomCheat(
    props.rom.id.toString(),
    cheat.id.toString(),
    {
      id: cheat.id.toString(),
      name: cheat.editName,
      code: cheat.editCode,
      description: cheat.editDescription,
      type: cheat.type,
      romId: props.rom.id.toString(),
    },
  );

  if (result) {
    await refreshCheats(); // Refresh cheats after updating
    cheat.isEditing = false;
  }
}

async function deleteCheat(cheatId: number) {
  if (!confirm(t("cheat.confirmDelete"))) return;

  const success = await deleteRomCheat(
    props.rom.id.toString(),
    cheatId.toString(),
  );

  if (success) {
    await refreshCheats(); // Refresh cheats after deleting
  }
}

async function handleUploadCheatFile() {
  if (!newCheatFile.value || !props.rom.id) return;

  const formData = new FormData();
  formData.append("file", newCheatFile.value);

  try {
    await uploadCheatFile(props.rom.id.toString(), formData);
    await refreshCheatFiles(); // fetch updated file list
    newCheatFile.value = null;
  } catch (err) {
    // Handle Error
  }
}

async function handleDeleteCheatFile(fileId: string) {
  try {
    await deleteCheatFile(props.rom.id.toString(), fileId);
    await refreshCheatFiles();
  } catch (err) {
    // Handle Error
  }
}

// Reload cheat file list after upload/delete
async function refreshCheatFiles() {
  try {
    const { data } = await getCheatFiles(props.rom.id.toString());
    // @ts-ignore
    props.rom.cheat_files = data;
  } catch {
    // Handle Error
  }
}

function formatBytes(bytes: number): string {
  if (!bytes) return "0 B";
  const sizes = ["B", "KB", "MB", "GB"];
  const i = Math.floor(Math.log(bytes) / Math.log(1024));
  return `${(bytes / Math.pow(1024, i)).toFixed(1)} ${sizes[i]}`;
}

function formatDate(date: string): string {
  return new Date(date).toLocaleDateString();
}

// Define cheat types and their formatted display values
const cheatTypes = [
  { value: "raw", text: "Raw" },
  { value: "game_genie", text: "Game Genie" },
  { value: "gameshark", text: "GameShark" },
  { value: "codebreaker", text: "CodeBreaker" },
  { value: "actionreplay", text: "ActionReplay" },
];

function formatCheatType(type: string): string {
  const typeMap: Record<string, string> = {
    raw: "Raw",
    game_genie: "Game Genie",
    gameshark: "GameShark",
    codebreaker: "CodeBreaker",
    actionreplay: "ActionReplay",
  };
  return typeMap[type] || type;
}
</script>

<template>
  <v-card-text class="pa-4">
    <v-row no-gutters>
      <v-col cols="12" lg="2">
        <v-tabs
          v-model="activeTab"
          :direction="mdAndDown ? 'horizontal' : 'vertical'"
          :align-tabs="mdAndDown ? 'center' : 'start'"
          slider-color="secondary"
          class="mr-4 mt-2"
          selected-class="bg-toplayer"
        >
          <v-tab
            prepend-icon="mdi-code-array"
            class="rounded text-caption"
            value="cheatcodes"
            >{{ t("cheat.cheatCodes") || "Cheat Codes" }}</v-tab
          >
          <v-tab
            prepend-icon="mdi-file-document"
            class="rounded text-caption"
            value="cheatfiles"
            >{{ t("cheat.cheatFiles") || "Cheat Files" }}</v-tab
          >
        </v-tabs>
      </v-col>
      <v-col>
        <v-tabs-window v-model="activeTab">
          <!-- Cheat Codes Tab -->
          <v-tabs-window-item value="cheatcodes">
            <v-card class="mt-4">
              <v-card-title class="bg-toplayer">
                <v-list-item class="pl-2 pr-0">
                  <span class="text-h6">{{ t("rom.cheats") }}</span>
                </v-list-item>
              </v-card-title>
              <v-table>
                <thead>
                  <tr>
                    <th>{{ t("cheat.name") }}</th>
                    <th>{{ t("cheat.code") }}</th>
                    <th>{{ t("cheat.description") }}</th>
                    <th>{{ t("cheat.type") }}</th>
                    <th class="text-center">{{ t("common.actions") }}</th>
                  </tr>
                </thead>
                <tbody>
                  <tr v-for="cheat in cheats" :key="cheat.id">
                    <td>
                      <template v-if="cheat.isEditing">
                        <v-text-field
                          v-model="cheat.editName"
                          density="compact"
                          variant="outlined"
                          hide-details
                        />
                      </template>
                      <template v-else>
                        {{ cheat.name }}
                      </template>
                    </td>
                    <td>
                      <template v-if="cheat.isEditing">
                        <v-text-field
                          v-model="cheat.editCode"
                          density="compact"
                          variant="outlined"
                          hide-details
                        />
                      </template>
                      <template v-else>
                        <code>{{ cheat.code }}</code>
                      </template>
                    </td>
                    <td>
                      <template v-if="cheat.isEditing">
                        <v-text-field
                          v-model="cheat.editDescription"
                          density="compact"
                          variant="outlined"
                          hide-details
                        />
                      </template>
                      <template v-else>
                        {{ cheat.description }}
                      </template>
                    </td>
                    <td>
                      <template v-if="cheat.isEditing">
                        <v-select
                          v-model="cheat.type"
                          :items="cheatTypes"
                          item-title="text"
                          item-value="value"
                          density="compact"
                          variant="outlined"
                          hide-details
                        />
                      </template>
                      <template v-else>
                        {{
                          cheat.formattedType ||
                          formatCheatType(cheat.type || "raw")
                        }}
                      </template>
                    </td>
                    <td class="text-center">
                      <v-btn
                        icon
                        density="comfortable"
                        @click="
                          cheat.isEditing ? saveEdit(cheat) : toggleEdit(cheat)
                        "
                        :disabled="!scopes.includes('roms.user.write')"
                      >
                        <v-icon>
                          {{ cheat.isEditing ? "mdi-check" : "mdi-pencil" }}
                        </v-icon>
                      </v-btn>
                      <v-btn
                        icon
                        density="comfortable"
                        color="error"
                        @click="deleteCheat(cheat.id)"
                        :disabled="!scopes.includes('roms.user.write')"
                      >
                        <v-icon>mdi-delete</v-icon>
                      </v-btn>
                    </td>
                  </tr>
                </tbody>
              </v-table>

              <v-divider class="my-4" />

              <v-row class="align-center">
                <v-col cols="12" md="3">
                  <v-text-field
                    v-model="newCheat.name"
                    :label="t('cheat.name')"
                    density="compact"
                    variant="outlined"
                    hide-details
                  />
                </v-col>
                <v-col cols="12" md="3">
                  <v-text-field
                    v-model="newCheat.code"
                    :label="t('cheat.code')"
                    density="compact"
                    variant="outlined"
                    hide-details
                  />
                </v-col>
                <v-col cols="12" md="4">
                  <v-text-field
                    v-model="newCheat.description"
                    :label="t('cheat.description')"
                    density="compact"
                    variant="outlined"
                    hide-details
                  />
                </v-col>
                <v-col cols="12" md="2">
                  <v-select
                    v-model="newCheat.type"
                    :items="cheatTypes"
                    item-title="text"
                    item-value="value"
                    :label="t('cheat.type')"
                    density="compact"
                    variant="outlined"
                    hide-details
                  />
                </v-col>
                <v-col cols="12" md="2">
                  <v-btn
                    color="primary"
                    block
                    :disabled="
                      !newCheat.name ||
                      !newCheat.code ||
                      !scopes.includes('roms.user.write')
                    "
                    @click="addCheat"
                    data-test="add-cheat-button"
                  >
                    {{ t("cheat.add") }}
                  </v-btn>
                </v-col>
              </v-row>
            </v-card>
          </v-tabs-window-item>

          <!-- Cheat Files Tab -->
          <v-tabs-window-item value="cheatfiles">
            <!-- Upload Cheat File -->
            <v-file-input
              v-model="newCheatFile"
              :label="t('rom.uploadCheatFile')"
              accept=".txt,.db,.zip"
              show-size
              density="compact"
              variant="outlined"
              prepend-icon="mdi-upload"
              @change="handleUploadCheatFile"
            />

            <!-- Display existing cheat files if any -->
            <v-list
              v-if="
                Array.isArray(props.rom.cheat_files) &&
                props.rom.cheat_files.length
              "
            >
              <v-list-item
                v-for="(file, index) in props.rom.cheat_files"
                :key="index"
                class="px-0"
              >
                <template v-slot:prepend>
                  <v-icon icon="mdi-file-document" class="mr-2"></v-icon>
                </template>

                <v-list-item-title class="font-weight-medium">
                  {{ file.name }}
                </v-list-item-title>

                <v-list-item-subtitle>
                  {{ formatBytes((file as any).size) }} –
                  {{ formatDate((file as any).updated_at) }}
                </v-list-item-subtitle>

                <template v-slot:append>
                  <v-btn
                    icon
                    color="primary"
                    :href="(file as any).path"
                    target="_blank"
                    :title="t('common.view')"
                    class="mr-2"
                  >
                    <v-icon>mdi-open-in-new</v-icon>
                  </v-btn>

                  <v-btn
                    icon
                    color="error"
                    @click="handleDeleteCheatFile(file.id)"
                    :title="t('common.delete')"
                  >
                    <v-icon>mdi-delete</v-icon>
                  </v-btn>
                </template>
              </v-list-item>
            </v-list>

            <!-- Empty state message when no cheat files -->
            <v-alert v-else type="info" variant="tonal" class="mt-2">
              {{
                t("rom.noCheatFiles") ||
                "No cheat files uploaded yet. Use the input above to upload cheat files."
              }}
            </v-alert>
          </v-tabs-window-item>
        </v-tabs-window>
      </v-col>
    </v-row>
  </v-card-text>
</template>

<style scoped>
thead th {
  text-align: left;
  font-weight: 600;
  padding: 8px;
}

tbody td {
  padding: 8px;
  border-top: 1px solid #ddd;
  vertical-align: top;
}
</style>
