<script setup lang="ts">
import { ref, onMounted } from "vue";
import { useI18n } from "vue-i18n";
import { useTheme, useDisplay } from "vuetify";
import { storeToRefs } from "pinia";
import {
  addRomCheat,
  updateRomCheat,
  deleteRomCheat,
  uploadCheatFile,
  getCheatFiles,
  deleteCheatFile,
  getCheatCodes,
} from "@/services/api/cheat";
import romApi from "@/services/api/rom";
import storeAuth from "@/stores/auth";
import type { DetailedRom } from "@/stores/roms";
import type { CheatFile } from "@/services/api/cheat";

interface ExtendedCheatFile extends CheatFile {
  size: number;
  updated_at: string;
  path: string;
}

interface ExtendedDetailedRom extends DetailedRom {
  cheats?: any[];
  cheat_files?: CheatFile[];
}

const props = defineProps<{ rom: ExtendedDetailedRom }>();
const { t } = useI18n();
const theme = useTheme();
const auth = storeAuth();
const newCheatFile = ref<File | null>(null);
const { scopes } = storeToRefs(auth);
const activeTab = ref("cheatcodes");
const { mdAndDown } = useDisplay();

const loadingCheats = ref(false);
const loadingAddCheat = ref(false);
const loadingUpdateCheat = ref<Record<string, boolean>>({});
const loadingDeleteCheat = ref<Record<string, boolean>>({});
const loadingUploadCheatFile = ref(false);
const loadingDeleteCheatFile = ref<Record<string, boolean>>({});

const cheats = ref(
  (props.rom.cheats ?? []).map((cheat) => ({
    ...cheat,
    isEditing: false,
    editName: cheat.name,
    editCode: cheat.code,
    editDescription: cheat.description,
  })),
);

const newCheat = ref({
  name: "",
  code: "",
  description: "",
  type: "raw", // Default type
});

// Form validation
const errors = ref({
  name: "",
  code: "",
  description: "",
  type: "",
});

// Validate form fields
function validateField(field: string, value: string) {
  if (field === "name") {
    errors.value.name = !value
      ? t("cheat.nameRequired") || "Name is required"
      : "";
  } else if (field === "code") {
    errors.value.code = !value
      ? t("cheat.codeRequired") || "Code is required"
      : "";
  }
  // Type always has a default value, so no validation needed
  // Description is optional, so no validation needed
}

// Fetch cheats from the backend
async function refreshCheats() {
  loadingCheats.value = true;
  try {
    const response = await getCheatCodes(props.rom.id.toString());
    if (response && Array.isArray(response)) {
      cheats.value = response.map((cheat) => ({
        ...cheat,
        isEditing: false,
        editName: cheat.name,
        editCode: cheat.code,
        editDescription: cheat.description,
        type: cheat.type || "raw", // Ensure type is preserved and has a default
        formattedType: formatCheatType(cheat.type || "raw"), // Add formatted type for display
      }));
    }
  } catch (error) {
    console.error("Failed to fetch cheats:", error);
  } finally {
    loadingCheats.value = false;
  }
}

// Load cheats when component is mounted
onMounted(() => {
  refreshCheats();
  refreshCheatFiles();
});

async function addCheat() {
  // Validate all fields before submission
  validateField("name", newCheat.value.name);
  validateField("code", newCheat.value.code);

  // Check if there are any errors
  if (errors.value.name || errors.value.code) return;

  loadingAddCheat.value = true;
  try {
    console.log("Adding cheat:", newCheat.value);
    const result = await addRomCheat(props.rom.id.toString(), {
      id: "", // Will be generated by the server
      name: newCheat.value.name,
      code: newCheat.value.code,
      description: newCheat.value.description,
      type: newCheat.value.type,
      romId: props.rom.id.toString(),
    });

    console.log("Add cheat result:", result);
    if (result?.id) {
      await refreshCheats(); // Refresh cheats after adding
      newCheat.value = { name: "", code: "", description: "", type: "raw" }; // Reset to default values
    } else {
      console.error("Failed to add cheat code: No ID returned from server");
      alert(t("cheat.addFailed"));
    }
  } catch (error: any) {
    console.error("Failed to add cheat code:", error);
    alert(t("cheat.addFailed") + ": " + (error.message || "Unknown error"));
  } finally {
    loadingAddCheat.value = false;
  }
}

function toggleEdit(cheat: any) {
  cheat.isEditing = !cheat.isEditing;
}

async function saveEdit(cheat: any) {
  // Validate edit fields
  const editErrors = {
    name: !cheat.editName ? t("cheat.nameRequired") || "Name is required" : "",
    code: !cheat.editCode ? t("cheat.codeRequired") || "Code is required" : "",
  };

  // Check if there are any errors
  if (editErrors.name || editErrors.code) {
    // Show error messages temporarily
    if (editErrors.name) alert(editErrors.name);
    if (editErrors.code) alert(editErrors.code);
    return;
  }

  loadingUpdateCheat.value[cheat.id] = true;
  try {
    const result = await updateRomCheat(
      props.rom.id.toString(),
      cheat.id.toString(),
      {
        id: cheat.id.toString(),
        name: cheat.editName,
        code: cheat.editCode,
        description: cheat.editDescription,
        type: cheat.type,
        romId: props.rom.id.toString(),
      },
    );

    if (result) {
      await refreshCheats(); // Refresh cheats after updating
      cheat.isEditing = false;
    }
  } finally {
    loadingUpdateCheat.value[cheat.id] = false;
  }
}

async function deleteCheat(cheatId: number) {
  if (!confirm(t("cheat.confirmDelete"))) return;

  loadingDeleteCheat.value[cheatId] = true;
  try {
    const success = await deleteRomCheat(
      props.rom.id.toString(),
      cheatId.toString(),
    );

    if (success) {
      await refreshCheats(); // Refresh cheats after deleting
    }
  } finally {
    loadingDeleteCheat.value[cheatId] = false;
  }
}

async function handleUploadCheatFile() {
  if (!newCheatFile.value || !props.rom.id) return;

  loadingUploadCheatFile.value = true;
  const formData = new FormData();
  formData.append("file", newCheatFile.value);

  try {
    await uploadCheatFile(props.rom.id.toString(), formData);
    await refreshCheatFiles(); // fetch updated file list
    newCheatFile.value = null;
  } catch (err) {
    // Handle Error
  } finally {
    loadingUploadCheatFile.value = false;
  }
}

async function handleDeleteCheatFile(fileId: string) {
  loadingDeleteCheatFile.value[fileId] = true;
  try {
    await deleteCheatFile(props.rom.id.toString(), fileId);
    await refreshCheatFiles();
  } catch (err) {
    // Handle Error
  } finally {
    loadingDeleteCheatFile.value[fileId] = false;
  }
}

// Reload cheat file list after upload/delete
async function refreshCheatFiles() {
  try {
    const { data } = await getCheatFiles(props.rom.id.toString());
    // @ts-ignore
    props.rom.cheat_files = data;
  } catch {
    // Handle Error
  }
}

function formatBytes(bytes: number): string {
  if (!bytes) return "0 B";
  const sizes = ["B", "KB", "MB", "GB"];
  const i = Math.floor(Math.log(bytes) / Math.log(1024));
  return `${(bytes / Math.pow(1024, i)).toFixed(1)} ${sizes[i]}`;
}

function formatDate(date: string): string {
  return new Date(date).toLocaleDateString();
}

// Define cheat types and their formatted display values
const cheatTypes = [
  { value: "raw", text: "Raw" },
  { value: "game_genie", text: "Game Genie" },
  { value: "gameshark", text: "GameShark" },
  { value: "codebreaker", text: "CodeBreaker" },
  { value: "actionreplay", text: "ActionReplay" },
];

function formatCheatType(type: string): string {
  const typeMap: Record<string, string> = {
    raw: "Raw",
    game_genie: "Game Genie",
    gameshark: "GameShark",
    codebreaker: "CodeBreaker",
    actionreplay: "ActionReplay",
  };
  return typeMap[type] || type;
}
</script>

<template>
  <v-card-text class="pa-4">
    <v-row no-gutters>
      <v-col cols="12" lg="2">
        <v-tabs
          v-model="activeTab"
          :direction="mdAndDown ? 'horizontal' : 'vertical'"
          :align-tabs="mdAndDown ? 'center' : 'start'"
          slider-color="secondary"
          class="mr-4 mt-2"
          selected-class="bg-toplayer"
        >
          <v-tab
            prepend-icon="mdi-code-array"
            class="rounded text-caption"
            value="cheatcodes"
            >{{ t("cheat.cheatCodes") || "Cheat Codes" }}</v-tab
          >
          <v-tab
            prepend-icon="mdi-file-document"
            class="rounded text-caption"
            value="cheatfiles"
            >{{ t("cheat.cheatFiles") || "Cheat Files" }}</v-tab
          >
        </v-tabs>
      </v-col>
      <v-col>
        <v-tabs-window v-model="activeTab">
          <!-- Cheat Codes Tab -->
          <v-tabs-window-item value="cheatcodes">
            <v-card class="mt-4">
              <v-card-title class="bg-toplayer">
                <v-list-item class="pl-2 pr-0">
                  <span class="text-h6">{{ t("rom.cheats") }}</span>
                </v-list-item>
              </v-card-title>
              <v-table class="cheats-table">
                <thead>
                  <tr>
                    <th>{{ t("cheat.name") }}</th>
                    <th>{{ t("cheat.code") }}</th>
                    <th class="hide-on-small">{{ t("cheat.description") }}</th>
                    <th class="hide-on-small">{{ t("cheat.type") }}</th>
                    <th class="text-center">{{ t("common.actions") }}</th>
                  </tr>
                </thead>
                <tbody>
                  <tr v-for="cheat in cheats" :key="cheat.id">
                    <td>
                      <template v-if="cheat.isEditing">
                        <v-text-field
                          v-model="cheat.editName"
                          density="compact"
                          variant="outlined"
                          :error-messages="
                            !cheat.editName
                              ? t('cheat.nameRequired') || 'Name is required'
                              : ''
                          "
                        />
                      </template>
                      <template v-else>
                        {{ cheat.name }}
                      </template>
                    </td>
                    <td>
                      <template v-if="cheat.isEditing">
                        <v-text-field
                          v-model="cheat.editCode"
                          density="compact"
                          variant="outlined"
                          :error-messages="
                            !cheat.editCode
                              ? t('cheat.codeRequired') || 'Code is required'
                              : ''
                          "
                        />
                      </template>
                      <template v-else>
                        <code>{{ cheat.code }}</code>
                      </template>
                    </td>
                    <td class="hide-on-small">
                      <template v-if="cheat.isEditing">
                        <v-text-field
                          v-model="cheat.editDescription"
                          density="compact"
                          variant="outlined"
                          hide-details
                        />
                      </template>
                      <template v-else>
                        {{ cheat.description }}
                      </template>
                    </td>
                    <td class="hide-on-small">
                      <template v-if="cheat.isEditing">
                        <v-select
                          v-model="cheat.type"
                          :items="cheatTypes"
                          item-title="text"
                          item-value="value"
                          density="compact"
                          variant="outlined"
                          hide-details
                        />
                      </template>
                      <template v-else>
                        {{
                          cheat.formattedType ||
                          formatCheatType(cheat.type || "raw")
                        }}
                      </template>
                    </td>
                    <td class="text-center">
                      <v-btn
                        icon
                        density="comfortable"
                        @click="
                          cheat.isEditing ? saveEdit(cheat) : toggleEdit(cheat)
                        "
                        :disabled="
                          !scopes.includes('roms.user.write') ||
                          (cheat.isEditing && loadingUpdateCheat[cheat.id])
                        "
                      >
                        <v-icon>
                          <template
                            v-if="
                              cheat.isEditing && loadingUpdateCheat[cheat.id]
                            "
                          >
                            <v-progress-circular indeterminate size="20" />
                          </template>
                          <template v-else>
                            {{ cheat.isEditing ? "mdi-check" : "mdi-pencil" }}
                          </template>
                        </v-icon>
                      </v-btn>
                      <v-btn
                        icon
                        density="comfortable"
                        color="error"
                        @click="deleteCheat(cheat.id)"
                        :disabled="
                          !scopes.includes('roms.user.write') ||
                          loadingDeleteCheat[cheat.id]
                        "
                      >
                        <v-icon>
                          <template v-if="loadingDeleteCheat[cheat.id]">
                            <v-progress-circular
                              indeterminate
                              size="20"
                              color="error"
                            />
                          </template>
                          <template v-else> mdi-delete </template>
                        </v-icon>
                      </v-btn>
                    </td>
                  </tr>
                </tbody>
              </v-table>

              <v-divider class="my-4" />

              <v-row class="align-center">
                <v-col cols="12" sm="6" md="3">
                  <v-text-field
                    v-model="newCheat.name"
                    :label="t('cheat.name')"
                    density="compact"
                    variant="outlined"
                    :error-messages="errors.name"
                    @input="validateField('name', newCheat.name)"
                    @blur="validateField('name', newCheat.name)"
                    required
                  />
                </v-col>
                <v-col cols="12" sm="6" md="3">
                  <v-text-field
                    v-model="newCheat.code"
                    :label="t('cheat.code')"
                    density="compact"
                    variant="outlined"
                    :error-messages="errors.code"
                    @input="validateField('code', newCheat.code)"
                    @blur="validateField('code', newCheat.code)"
                    required
                  />
                </v-col>
                <v-col cols="12" sm="6" md="3">
                  <v-text-field
                    v-model="newCheat.description"
                    :label="t('cheat.description')"
                    density="compact"
                    variant="outlined"
                    hide-details
                  />
                </v-col>
                <v-col cols="12" sm="6" md="2">
                  <v-select
                    v-model="newCheat.type"
                    :items="cheatTypes"
                    item-title="text"
                    item-value="value"
                    :label="t('cheat.type')"
                    density="compact"
                    variant="outlined"
                    hide-details
                  />
                </v-col>
                <v-col cols="12" md="1">
                  <v-btn
                    color="primary"
                    block
                    :disabled="
                      !scopes.includes('roms.user.write') || loadingAddCheat
                    "
                    @click="addCheat"
                    data-test="add-cheat-button"
                  >
                    <template v-if="loadingAddCheat">
                      <v-progress-circular
                        indeterminate
                        size="20"
                        color="white"
                      />
                    </template>
                    <template v-else>
                      {{ t("cheat.add") }}
                    </template>
                  </v-btn>
                </v-col>
              </v-row>
            </v-card>
          </v-tabs-window-item>

          <!-- Cheat Files Tab -->
          <v-tabs-window-item value="cheatfiles">
            <!-- Upload Cheat File -->
            <v-card class="pa-4 mb-4">
              <v-file-input
                v-model="newCheatFile"
                :label="t('rom.uploadCheatFile')"
                accept=".txt,.db,.zip"
                show-size
                density="compact"
                variant="outlined"
                prepend-icon="mdi-upload"
                @change="handleUploadCheatFile"
                :disabled="
                  !scopes.includes('roms.user.write') || loadingUploadCheatFile
                "
                :hint="
                  t('cheat.supportedFormats') ||
                  'Supported formats: .txt, .db, .zip'
                "
                persistent-hint
              />
              <v-progress-linear
                v-if="loadingUploadCheatFile"
                indeterminate
                color="primary"
                class="mb-2"
              />
            </v-card>

            <!-- Display existing cheat files if any -->
            <v-card class="pa-4">
              <v-list
                v-if="
                  Array.isArray(props.rom.cheat_files) &&
                  props.rom.cheat_files.length
                "
                class="cheat-files-list"
              >
                <v-list-item
                  v-for="(file, index) in props.rom.cheat_files"
                  :key="index"
                  class="px-0 cheat-file-item mb-2"
                  :class="{ 'mb-3': mdAndDown }"
                  rounded
                  variant="outlined"
                >
                  <template v-slot:prepend>
                    <v-icon icon="mdi-file-document" class="mr-2"></v-icon>
                  </template>

                  <v-list-item-title class="font-weight-medium">
                    {{ file.name }}
                  </v-list-item-title>

                  <v-list-item-subtitle>
                    {{ formatBytes((file as any).size) }} –
                    {{ formatDate((file as any).updated_at) }}
                  </v-list-item-subtitle>

                  <template v-slot:append>
                    <v-btn
                      icon
                      color="primary"
                      :href="(file as any).path"
                      target="_blank"
                      :title="t('common.view')"
                      class="mr-2"
                    >
                      <v-icon>mdi-open-in-new</v-icon>
                    </v-btn>

                    <v-btn
                      icon
                      color="error"
                      @click="handleDeleteCheatFile(file.id)"
                      :title="t('common.delete')"
                      :disabled="
                        !scopes.includes('roms.user.write') ||
                        loadingDeleteCheatFile[file.id]
                      "
                    >
                      <v-icon>
                        <template v-if="loadingDeleteCheatFile[file.id]">
                          <v-progress-circular
                            indeterminate
                            size="20"
                            color="error"
                          />
                        </template>
                        <template v-else> mdi-delete </template>
                      </v-icon>
                    </v-btn>
                  </template>
                </v-list-item>
              </v-list>

              <!-- Empty state message when no cheat files -->
              <v-alert v-else type="info" variant="tonal" class="mt-2">
                {{
                  t("rom.noCheatFiles") ||
                  "No cheat files uploaded yet. Use the input above to upload cheat files."
                }}
              </v-alert>
            </v-card>
          </v-tabs-window-item>
        </v-tabs-window>
      </v-col>
    </v-row>
  </v-card-text>
</template>

<style scoped>
thead th {
  text-align: left;
  font-weight: 600;
  padding: 8px;
}

tbody td {
  padding: 8px;
  border-top: 1px solid #ddd;
  vertical-align: top;
}

/* Responsive styles */
@media (max-width: 600px) {
  .hide-on-small {
    display: none;
  }

  .cheats-table {
    font-size: 0.9rem;
  }

  tbody td {
    padding: 4px;
  }
}

/* Tablet adjustments */
@media (min-width: 601px) and (max-width: 960px) {
  .cheats-table {
    font-size: 0.95rem;
  }
}

/* Cheat files list styling */
.cheat-files-list {
  border-radius: 8px;
}

.cheat-file-item {
  transition: background-color 0.2s ease;
}

.cheat-file-item:hover {
  background-color: rgba(var(--v-theme-surface-variant), 0.1);
}

/* Add some spacing between form elements on mobile */
@media (max-width: 600px) {
  .v-col {
    padding-top: 8px;
    padding-bottom: 8px;
  }
}
</style>
